[
	{"lib/open_api_typesense/plugins/field.ex", "Unknown type: OpenAPI.Processor.Type.t/0."},
	{"lib/open_api_typesense/plugins/processor.ex", "Callback info about the OpenAPI.Processor behaviour is not available."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.ignore_operation?/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.ignore_schema?/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.operation_docstring/3 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.operation_function_name/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.operation_module_names/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.operation_request_body/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.operation_request_method/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.operation_response_body/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.schema_format/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.Naming.merge_schema/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.Naming.rename_schema/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.Naming.group_schema/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.Naming.readable_content_type/1 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Function OpenAPI.Processor.Naming.normalize_identifier/2 does not exist."},
	{"lib/open_api_typesense/plugins/processor.ex", "Unknown type: OpenAPI.Processor.State.t/0."},
	{"lib/open_api_typesense/plugins/processor.ex", "Unknown type: OpenAPI.Processor.Schema.t/0."},
	{"lib/open_api_typesense/plugins/processor.ex", "Unknown type: OpenAPI.Spec.Schema.t/0."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Callback info about the OpenAPI.Renderer behaviour is not available."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.format/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.location/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render_default_client/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render_moduledoc/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render_operation/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render_operation_doc/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render_operations/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render_schema/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render_schema_field_function/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.render_using/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.write/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Processor.Naming.normalize_identifier/1 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.Operation.render_query/1 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.Util.clean_list/1 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.Operation.render_call_request_info/3 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.Util.to_readable_type/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.Util.to_type/2 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Function OpenAPI.Renderer.Util.put_newlines/1 does not exist."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Unknown type: OpenAPI.Renderer.State.t/0."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Unknown type: OpenAPI.Processor.Operation.t/0."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Unknown type: OpenAPI.Processor.Schema.t/0."},
	{"lib/open_api_typesense/plugins/renderer.ex", "Unknown type: OpenAPI.Processor.Schema.Field.t/0."},
]