defmodule OpenApiTypesense.SearchParameters do
  @moduledoc """
  Provides struct and type for a SearchParameters
  """
  use OpenApiTypesense.Encoder

  @type t :: %__MODULE__{
          cache_ttl: integer,
          conversation: boolean,
          conversation_id: String.t(),
          conversation_model_id: String.t(),
          curation_tags: String.t(),
          drop_tokens_mode: String.t(),
          drop_tokens_threshold: integer,
          enable_analytics: boolean,
          enable_curations: boolean,
          enable_highlight_v1: boolean,
          enable_synonyms: boolean,
          enable_typos_for_alpha_numerical_tokens: boolean,
          enable_typos_for_numerical_tokens: boolean,
          exclude_fields: String.t(),
          exhaustive_search: boolean,
          facet_by: String.t(),
          facet_query: String.t(),
          facet_return_parent: String.t(),
          facet_strategy: String.t(),
          filter_by: String.t(),
          filter_curated_hits: boolean,
          group_by: String.t(),
          group_limit: integer,
          group_missing_values: boolean,
          hidden_hits: String.t(),
          highlight_affix_num_tokens: integer,
          highlight_end_tag: String.t(),
          highlight_fields: String.t(),
          highlight_full_fields: String.t(),
          highlight_start_tag: String.t(),
          include_fields: String.t(),
          infix: String.t(),
          limit: integer,
          max_candidates: integer,
          max_extra_prefix: integer,
          max_extra_suffix: integer,
          max_facet_values: integer,
          max_filter_by_candidates: integer,
          min_len_1typo: integer,
          min_len_2typo: integer,
          nl_model_id: String.t(),
          nl_query: boolean,
          num_typos: String.t(),
          offset: integer,
          page: integer,
          per_page: integer,
          pinned_hits: String.t(),
          pre_segmented_query: boolean,
          prefix: String.t(),
          preset: String.t(),
          prioritize_exact_match: boolean,
          prioritize_num_matching_fields: boolean,
          prioritize_token_position: boolean,
          q: String.t(),
          query_by: String.t(),
          query_by_weights: String.t(),
          remote_embedding_num_tries: integer,
          remote_embedding_timeout_ms: integer,
          search_cutoff_ms: integer,
          snippet_threshold: integer,
          sort_by: String.t(),
          split_join_tokens: String.t(),
          stopwords: String.t(),
          synonym_num_typos: integer,
          synonym_prefix: boolean,
          synonym_sets: String.t(),
          text_match_type: String.t(),
          typo_tokens_threshold: integer,
          use_cache: boolean,
          validate_field_names: boolean,
          vector_query: String.t(),
          voice_query: String.t()
        }

  defstruct [
    :cache_ttl,
    :conversation,
    :conversation_id,
    :conversation_model_id,
    :curation_tags,
    :drop_tokens_mode,
    :drop_tokens_threshold,
    :enable_synonyms,
    :enable_typos_for_alpha_numerical_tokens,
    :exclude_fields,
    :exhaustive_search,
    :facet_by,
    :facet_query,
    :facet_return_parent,
    :facet_strategy,
    :filter_by,
    :filter_curated_hits,
    :group_by,
    :group_limit,
    :group_missing_values,
    :hidden_hits,
    :highlight_affix_num_tokens,
    :highlight_end_tag,
    :highlight_fields,
    :highlight_full_fields,
    :highlight_start_tag,
    :include_fields,
    :infix,
    :limit,
    :max_candidates,
    :max_extra_prefix,
    :max_extra_suffix,
    :max_facet_values,
    :max_filter_by_candidates,
    :min_len_1typo,
    :min_len_2typo,
    :nl_model_id,
    :nl_query,
    :num_typos,
    :offset,
    :page,
    :per_page,
    :pinned_hits,
    :pre_segmented_query,
    :prefix,
    :preset,
    :q,
    :query_by,
    :query_by_weights,
    :remote_embedding_num_tries,
    :remote_embedding_timeout_ms,
    :search_cutoff_ms,
    :snippet_threshold,
    :sort_by,
    :split_join_tokens,
    :stopwords,
    :synonym_num_typos,
    :synonym_prefix,
    :synonym_sets,
    :text_match_type,
    :typo_tokens_threshold,
    :use_cache,
    :validate_field_names,
    :vector_query,
    :voice_query,
    enable_analytics: true,
    enable_curations: false,
    enable_highlight_v1: true,
    enable_typos_for_numerical_tokens: true,
    prioritize_exact_match: true,
    prioritize_num_matching_fields: true,
    prioritize_token_position: false
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      cache_ttl: :integer,
      conversation: :boolean,
      conversation_id: :string,
      conversation_model_id: :string,
      curation_tags: :string,
      drop_tokens_mode: {:enum, ["right_to_left", "left_to_right", "both_sides:3"]},
      drop_tokens_threshold: :integer,
      enable_analytics: :boolean,
      enable_curations: :boolean,
      enable_highlight_v1: :boolean,
      enable_synonyms: :boolean,
      enable_typos_for_alpha_numerical_tokens: :boolean,
      enable_typos_for_numerical_tokens: :boolean,
      exclude_fields: :string,
      exhaustive_search: :boolean,
      facet_by: :string,
      facet_query: :string,
      facet_return_parent: :string,
      facet_strategy: :string,
      filter_by: :string,
      filter_curated_hits: :boolean,
      group_by: :string,
      group_limit: :integer,
      group_missing_values: :boolean,
      hidden_hits: :string,
      highlight_affix_num_tokens: :integer,
      highlight_end_tag: :string,
      highlight_fields: :string,
      highlight_full_fields: :string,
      highlight_start_tag: :string,
      include_fields: :string,
      infix: :string,
      limit: :integer,
      max_candidates: :integer,
      max_extra_prefix: :integer,
      max_extra_suffix: :integer,
      max_facet_values: :integer,
      max_filter_by_candidates: :integer,
      min_len_1typo: :integer,
      min_len_2typo: :integer,
      nl_model_id: :string,
      nl_query: :boolean,
      num_typos: :string,
      offset: :integer,
      page: :integer,
      per_page: :integer,
      pinned_hits: :string,
      pre_segmented_query: :boolean,
      prefix: :string,
      preset: :string,
      prioritize_exact_match: :boolean,
      prioritize_num_matching_fields: :boolean,
      prioritize_token_position: :boolean,
      q: :string,
      query_by: :string,
      query_by_weights: :string,
      remote_embedding_num_tries: :integer,
      remote_embedding_timeout_ms: :integer,
      search_cutoff_ms: :integer,
      snippet_threshold: :integer,
      sort_by: :string,
      split_join_tokens: :string,
      stopwords: :string,
      synonym_num_typos: :integer,
      synonym_prefix: :boolean,
      synonym_sets: :string,
      text_match_type: :string,
      typo_tokens_threshold: :integer,
      use_cache: :boolean,
      validate_field_names: :boolean,
      vector_query: :string,
      voice_query: :string
    ]
  end
end
